spring:
  datasource:
    url: jdbc:mysql://119.23.54.155:3306/designer
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接大小
    druid:
      min-idle: 5
      max-active: 10
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800


mypro:
  message:
    username: root
    password: root